DROP USER c##product CASCADE;
-- 계정 생성
CREATE USER c##product IDENTIFIED BY product1234
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  PROFILE DEFAULT;
-- 권한 부여
GRANT CONNECT, RESOURCE TO c##product;
GRANT CREATE VIEW, CREATE SYNONYM TO c##product;
GRANT UNLIMITED TABLESPACE TO c##product;
--락 풀기기
ALTR USER c##product ACCOUNT UNLOCK;